spring:
  server:
    port: 8080
  application:
    name: backend_dev
  # JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/dev?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=false
    username: root
    # password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
  console:
    enabled: true
  cloud:
    gcp:
      sql:
        enabled: false
      storage:
        enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    session:
      cookie:
        same-site: "None"
        secure: true
# ----------------------------------------
# GLOBAL PROPERTIES
# ----------------------------------------

# ----------------------------------------
# LOGGING PROPERTIES
# ----------------------------------------
logging:
  level:
    org:
      springframework:
        web: INFO
  file: logs/backend.log